
USE PLANETARYGOODS;

/*
1. BUSINESS REPORTING
*/

SELECT MONTH(ORDERDATE) AS MONTH, 
	YEAR(ORDERDATE) AS YEAR, 
    SUM(TOTALPAID) AS TOTALSALES
FROM ORDERS
GROUP BY YEAR(ORDERDATE), MONTH(ORDERDATE);

-- AVERAGE SALES PER CUSTOMER
SELECT CUSTOMERID, AVG(TOTALPAID) AS AVERAGESALES
FROM ORDERS
GROUP BY CUSTOMERID;

-- HIGHEST AND LOWEST SELLING PRODUCTS
SELECT PRODUCTID, SUM(QUANTITY) AS TOTALQUANTITY
FROM ORDERDETAILS
GROUP BY PRODUCTID
ORDER BY TOTALQUANTITY DESC;





/*
2. ANALYZING USER BEHAVIOR 
*/

-- NUMBER OF ACTIVE USERS PER DAY
SELECT DATE(ACTIVITYTIMESTAMP) AS DATE, 
	COUNT(DISTINCT USERID) AS ACTIVEUSERS
FROM USERACTIVITY
GROUP BY DATE(ACTIVITYTIMESTAMP);

-- AVERAGE SESSION LENGTH
SELECT USERID, AVG(SESSIONLENGTH) AS AVERAGESESSIONLENGTH
FROM USERSESSIONS
GROUP BY USERID;




/*
3. PERFORMANCE MONITORING
*/

-- AVERAGE RESPONSE TIME
SELECT WEBSERVICE, AVG(RESPONSETIME) AS AVERAGERESPONSETIME
FROM WEBSERVICELOGS
GROUP BY WEBSERVICE;

-- MAXIMUM MEMORY USAGE
SELECT APPLICATION, MAX(MEMORYUSAGE) AS MAXMEMORYUSAGE
FROM APPLICATIONLOGS
GROUP BY APPLICATION;
